services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env           # dove metti HF_TOKEN e LLM_MODEL_URL
    volumes:
      - llama_models:/app/models # modello persistente
    ports:
      - "8000:8000"



  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: recover_frontend:latest
    ports:
      - "80:80"
    # in dev, per cache di npm
    volumes:
      - node_modules:/app/node_modules

volumes:
  llama_models:
  node_modules:
